# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.14.2
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_version: 12.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: 'This project will enable real life GIS support on Odoo/OpenERP.

    ## Storing your data

    All of your spatial data will be stored using robust dataformat provided by PostGIS.
    Projections, complex geometry formats (ploygon, lines, dot, donuts, multi-polygon,
    etc) are supported. You can import your spatial data with ease using WKT and CSV
    or by drawing them directly in Web client.

    ## Map Visualization and administration

    Background map and layers can be configured in the administration part. Various
    background sources are available:

    - OpenStreetMap, - SwissTopo, - Any WMS sources.

    Data layers can also easily be configured using any geometry columns of your system.
    Styling like choropleth, propotional symbols etc are available.

    ## Querying

    You data can be queried using various visual tools from your map view. Standard
    Odoo/OpenERP queries are supported and geographical operators in UI will be available.

    ## Referencing

    Customers can be georeferenced using open data services

    ## Extending

    A geospatial API is provided, to add your own functionalites at your convenience


    ## Requirements

    * System: *  **PostGIS** http://postgis.refractions.net/

    * Python: *  **Shapely** http://pypi.python.org/pypi/Shapely

    *  **geojson** http://pypi.python.org/pypi/geojson'
repo_name: Geospatial Addons for Odoo
repo_slug: geospatial
repo_website: https://github.com/OCA/geospatial
travis_apt_packages: []
travis_apt_sources: []

