[project]
name = "odoo-addons-oca-geospatial"
version = "18.0.20251117.1"
dependencies = [
    "odoo-addon-base_geoengine==18.0.*",
    "odoo-addon-web_leaflet_lib==18.0.*",
    "odoo-addon-web_view_leaflet_map==18.0.*",
    "odoo-addon-web_view_leaflet_map_partner==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
