[project]
name = "odoo-addons-oca-geospatial"
version = "19.0.20261002.0"
dependencies = [
    "odoo-addon-base_google_map==19.0.*",
    "odoo-addon-web_leaflet_lib==19.0.*",
    "odoo-addon-web_view_google_map==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
